### ISSUE TITLE
2FA support

### ISSUE THREAD

**Issue by LLMChild** [coffebar/transfer.nvim#10]
Great plugins!
Is there any chance that transfer.nvim can add a input box for 2FA authorize ?

**Comment by coffebar** [comment]
Hi, it's interesting. 
Did you use rsync with 2FA?
Can you show an example how to provide 2FA code to rsync? How it consumes codes?

**Comment by LLMChild** [comment]
It's ssh's 2FA.
You can get some documents from some place like this:https://medium.com/@prateek.malhotra004/enhancing-ssh-security-with-two-factor-authentication-2fa-via-pam-and-google-authenticator-70af135c2a95
I think rsync should have some argument to pass this 2FA code or something like this.
Now I use rsync command to transfer , it will have a prompt for 2FA.
But it would be come with error with your plugin and without 2FA prompt.
I checked your rsync command and I don't know why.
I will try later.

**Comment by coffebar** [comment]
> I think rsync should have some argument to pass this 2FA code or something like that.

I didn't find something like that in `man rsync`, tell me if you will find.

So, for now, rsync just asking you for 2FA in interactive mode? Not sure if possible to handle it from lua

**Comment by LLMChild** [comment]
Year, I tried.
It seems to be unrelated with rsync. I try to debug what happened exactly. I want to find the actual rsync command executed by Transfer.nvim, can you please tell me how to achieve that?

**Comment by coffebar** [comment]
The simplest way to see rsync command is to use `:TransferDirDiff [path]` command:
 
![image](https://github.com/coffebar/transfer.nvim/assets/3100053/3438f500-6578-4cea-83e2-4c221fd0110c)

 these 3 lines joined by space will be a command.

**Comment by coffebar** [comment]
Please Look into code how cli commands build for other functions https://github.com/coffebar/transfer.nvim/blob/54c1fae4bde80fa4d870e2910f65ca6b1fd74b37/lua/transfer/transfer.lua#L315C1-L328C6

**Comment by LLMChild** [comment]
Thank you! I think everything works well now.
