### ISSUE TITLE
Support for SFTP

### ISSUE THREAD

**Issue by DelinQu** [coffebar/transfer.nvim#12]
Hi [coffebar](https://github.com/coffebar), 
Thanks for your amazing work! I use a remote machine with SCP closed and only provide SFTP service for security. Thus, I can only connect to the service with SSH, Vscode, etc., and transfer files by SFTP. Do you have any plans to integrate SFTP cmd? Thanks a lot! 🤗

**Comment by coffebar** [comment]
Hi, this plugin uses scp and rsync and has no UI to input passwords. 
Unfortunately, rsync does not support sftp, but you can [mount the remote](https://serverfault.com/a/313382) as a filesystem and use rsync (with plugin or not) then for mounted path.

Of course, it will be great to add some functionality to make it possible, but it requires some additional software. You can investigate alternatives like lftp and csync, and if it will work the same way as rsync and scp, we can make a "switch" in config and adjust CLI commands

**Comment by DelinQu** [comment]
Thanks! I tried mounting a `remote machine` directory to a `local machine` directory, `/tmp/sshfs`, and using transfer.nvim plugins to sync files from the `local machine`. But it can't download any files from the local machine, e.g. `openvla/` (only the dir name, not all the inner files). However, if I manually create a `test/` dir in the local machine `/tmp/sshfs`, the plugin works well and downloads all the files in the test. I thinks this issue must be that sshfs only sync files when read/modify the files, thus transfer.nvm can't recognize all the files.

Notice the left upper corner, transfer.nvim download all the files in `test/` but only the dir of `openvla`: 
![image](https://github.com/coffebar/transfer.nvim/assets/60593268/6dc03f99-aef9-424f-bf46-211b3e5a19ab)

**Comment by coffebar** [comment]
I hope you will figure out what is going on wrong, maybe it's permissions or something. Unsure if possible to use the scp command on local filesystems, but rsync will work just fine. Rsync will be used by this plugin in case you are syncing some dir, not just single file

**Comment by DelinQu** [comment]
Yeah, I finally found that `sshfs` causes some delay, it might not be an ideal solution for a scp-and-rsync-forbidden cluster. It's really tough for a new nvim guy to create a good remote nvim dev workflow after lots of plugins try 😥.  Transfer.nvim is the most suitable way until now.

**Comment by coffebar** [comment]
transfer.nvim is something suitable for hotfixing, but for real development workflow I recommend using pipeline deployment, for example GitHub Actions, or just git hooks, if ci/cd tools are kinda overkill for your needs
