### ISSUE TITLE
ignore files 

### ISSUE THREAD

**Issue by GrimalDev** [coffebar/transfer.nvim#13]
Hello,

Would it be possible to ignore files while uploading? It seems that the exclude in the rsync has explicitly been configured for directories.

Thank you in advance and sorry if I missed something in the man...

**Comment by coffebar** [comment]
rsync has a param `--exclude=PATTERN`, which is used by transfer.nvim 

You can create any PATTERN, for example, by default `*.pyc` pattern [is excluded](https://github.com/coffebar/transfer.nvim/blob/54c1fae4bde80fa4d870e2910f65ca6b1fd74b37/lua/transfer/config.lua#L35).

Read `man rsync` section "FILTER RULES" for more details.

Let me know if transfer.nvim incorrectly passes commands to rsync

**Comment by GrimalDev** [comment]
Thank you for the quick response and the clarification, i've tried it with the following patterns:
- "*.local",
- ".env*"
- ".env.local"
But my ".env.local" Always gets uploaded.

**Comment by coffebar** [comment]
Confirmed issue, will be fixed

**Comment by coffebar** [comment]
The last change fixes support for patterns like ".env*".

**Comment by GrimalDev** [comment]
> The last change fixes support for patterns like ".env*".

work as anyone would think, it's perfect, thank you
