### ISSUE TITLE
a advice about Suggested mappings fo neo-tree

### ISSUE THREAD

**Issue by andywu1998** [coffebar/transfer.nvim#9]
the mappings all start with 'u'，but I can't press u when the cursor in neo-tree, the neovim will notify can't changed, because of the modifiable is cloesed(my neovim notify Chinese so I translate the notification manually)

![image](https://github.com/coffebar/transfer.nvim/assets/30118280/c4605695-3fcf-47e0-8385-10643d9b5e1d)

so maybe you can change the prefix of Suggested mapping for the neo-tree

this is the Suggested mapping from the README: 
```
{
  window = {
    mappings = {
      -- upload (sync files)
      uu = {
        function(state)
          vim.cmd("TransferUpload " .. state.tree:get_node().path)
        end,
        desc = "upload file or directory",
        nowait = true,
      },
      -- download (sync files)
      ud = {
        function(state)
          vim.cmd("TransferDownload" .. state.tree:get_node().path)
        end,
        desc = "download file or directory",
        nowait = true,
      },
      -- diff directory with remote
      uf = {
        function(state)
          local node = state.tree:get_node()
          local context_dir = node.path
          if node.type ~= "directory" then
            -- if not a directory
            -- one level up
            context_dir = context_dir:gsub("/[^/]*$", "")
          end
          vim.cmd("TransferDirDiff " .. context_dir)
          vim.cmd("Neotree close")
        end,
        desc = "diff with remote",
      },
    },
  },
}
```

btw, this plugin is so well to use, thank you!

**Comment by coffebar** [comment]
This can happen if you are not in Normal mode. 
By default, Neo-tree is in Normal, so this should work with `u` prefix. 
Or maybe you need to adjust timeout between key presses (how much time should neovim to wait after press u). I believe it's `vim.o.timeoutlen`. For me, 500 (ms) is enough to press 2 keys

**Comment by andywu1998** [comment]
> This can happen if you are not in Normal mode. By default, Neo-tree is in Normal, so this should work with `u` prefix. Or maybe you need to adjust timeout between key presses (how much time should neovim to wait after press u). I believe it's `vim.o.timeoutlen`. For me, 500 (ms) is enough to press 2 keys

thanks your suggestion! 

my neo-tree always not in Normal mode, even I press Esc.

**Comment by coffebar** [comment]
Interesting, I don't see options to change the default mode for neotree. Maybe you did it from some custom event handler? 
When neotree is focused, what do you have in
`:echo mode`
?

**Comment by andywu1998** [comment]
> Interesting, I don't see options to change the default mode for neotree. Maybe you did it from some custom event handler? When neotree is focused, what do you have in `:echo mode` ?

When Neotree is focused, I run the command :echo mode() and it returns 'n', indicating that I am actually in Normal mode. My previous comment contained a mistake, and I apologize for that.

However, I have discovered that when I focus on an edit window, press Esc to enter Normal mode, and then press 'u', it performs an undo action, reverting the last change. This means that even when Neotree is focused and Neovim is in Normal mode, it is still possible to undo actions within Neotree.

**Comment by andywu1998** [comment]
![image](https://github.com/coffebar/transfer.nvim/assets/30118280/5d95288e-abf7-4887-adc2-36b5f2a5a829)

here is the mapping of neotree, it shows when the neotree is focused and I press '?'

there is no a mapping start with 'u', haha

**Comment by coffebar** [comment]
![image](https://github.com/coffebar/transfer.nvim/assets/3100053/5013b640-14e5-400b-ac0e-f6371aa267c5)

maybe try to scroll more, or you didn't set up it right

**Comment by coffebar** [comment]
for me U does nothing good except my bindings, just spawning not-modifiable buffer errors

**Comment by andywu1998** [comment]
yes, you are right,  I didn't set up it right.

now I finally solved the problem.

because I use lazynvim to do package manage. so I tried to edit my `nvim/lua/plugins/neo-tree.lua` like blow, the problem is solved

 
```nvim/lua/plugins/neo-tree.lua
{
        "nvim-neo-tree/neo-tree.nvim",
        opts = {
            filesystem = {
                filtered_items = {
                    visible = true,
                    show_hidden_count = true,
                    hide_dotfiles = false,
                    hide_gitignored = true,
                    hide_by_name = {
                        -- '.git',
                        -- '.DS_Store',
                        -- 'thumbs.db',
                    },
                    never_show = {},
                },
            },
            window = {
                mappings = {
                    -- upload (sync files)
                    uu = {
                        function(state)
                        vim.cmd("TransferUpload " .. state.tree:get_node().path)
                        end,
                        desc = "upload file or directory",
                        nowait = true,
                    },
                    -- download (sync files)
                    ud = {
                        function(state)
                        vim.cmd("TransferDownload" .. state.tree:get_node().path)
                        end,
                        desc = "download file or directory",
                        nowait = true,
                    },
                    -- diff directory with remote
                    uf = {
                        function(state)
                        local node = state.tree:get_node()
                        local context_dir = node.path
                        if node.type ~= "directory" then
                            -- if not a directory
                            -- one level up
                            context_dir = context_dir:gsub("/[^/]*$", "")
                        end
                        vim.cmd("TransferDirDiff " .. context_dir)
                        vim.cmd("Neotree close")
                        end,
                        desc = "diff with remote",
                    },
                }
            },
        },
    }
```

In the afternoon, I edit my nvim/config/neo-tree.lua like blow, it doesn't show the mapping when I press '?' in neo-tree.

At that time I see the README of this repo and I searched find how to set the neo-tree on google, and I found this method that doesn't work. I found the right way to set up the mapping of neotree (what I write above in nvim/lua/plugins/neo-tree.lua). 

so, although I don't know why this method doesn's work, but I found the right way, haha. (and if you know why, tell me please)

```
require("neo-tree").setup(
{
  window = {
    mappings = {
      -- upload (sync files)
      uu = {
        function(state)
          vim.cmd("TransferUpload " .. state.tree:get_node().path)
        end,
        desc = "upload file or directory",
        nowait = true,
      },
      -- download (sync files)
      ud = {
        function(state)
          vim.cmd("TransferDownload" .. state.tree:get_node().path)
        end,
        desc = "download file or directory",
        nowait = true,
      },
      -- diff directory with remote
      uf = {
        function(state)
          local node = state.tree:get_node()
          local context_dir = node.path
          if node.type ~= "directory" then
            -- if not a directory
            -- one level up
            context_dir = context_dir:gsub("/[^/]*$", "")
          end
          vim.cmd("TransferDirDiff " .. context_dir)
          vim.cmd("Neotree close")
        end,
        desc = "diff with remote",
      },
    },
  },
}
)
```


thank you again!!!

**Comment by coffebar** [comment]
Not a first time I hear lazyvim doesn't do what expected, you're welcome
